# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a85a82fd513a64d99b9525d56e9983931df52e62703cbbfb96f18859528ff05ae12cf661bdf18c4e59d7e775790ad0798358fa95ea19304127cceef83129fc8d

test:
  secret_key_base: 7f89ebf0bef138b6215f1855c4ffa8caa49cc404d0d5f0cd0a57465a32dbdc9bf65e635ded86afac7b70dbaa4ee87062cb7c37b52f31564035f91e46d6784f8f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
